name: Deploy to GitHub pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18.1'
    - name: Setup Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.19.4'
    - name: Build frontend
      run: ./scripts/build_frontend.sh
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./webui/build
