name: Deploy to GitHub pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18.1'
    - name: Setup Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.19.4'
    - name: Build frontend
      run: ./scripts/build_frontend.sh
    - name: Create repo
      run: |
        cd ./build
        git init
        git add -A
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m 'deploy'
    - name: Push to destination branch
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
        directory: ./build
